### ISSUE TITLE
conflict with plugin bigboard.

### ISSUE THREAD

**Issue by BI3QXJ** [Confexion/Greenwing#2]
after I have this theme installed, task cannot be move by drag. when I uninstall 'bigboard', it seems ok now. so I choose this one.

**Comment by jbaubree** [comment]
Hello,
do you have more plugins than Greenwing and Bigboard? I have just tested this two plugins at the same time and there is no problem to drag and drop tasks..
Bigboard project have no longer maintain or support. For layout issues, i can not fix because no support prevent me for PR.
I hope that answers your question

**Comment by BI3QXJ** [comment]
Also have cutomizer, calendar, gantt, minimize_sidebar, overwrite_translation and some others without impact on layout, thx for your help. with more test, I will offer you more detail about this bug.
Greenwing is my favourite theme, thx for your effort.
