### ISSUE TITLE
Cant Install this

### ISSUE THREAD

**Issue by isampa** [Confexion/Greenwing#37]
This Plugin cant Install.Can You Check it?
![screenshot-1612005382224 (1)](https://user-images.githubusercontent.com/56715009/106354880-c2986980-631a-11eb-8086-a70e526523fd.png)

**Comment by ronnyandre** [comment]
Same issue here.

**Comment by jbaubree** [comment]
Hello,

Thank you for your report, i will try to fix this issue ASAP.
You can for now download directly Greenwing theme from: https://github.com/Confexion/Greenwing/archive/master.zip
unzip this and place it in Plugins folder.

**Comment by suniahk** [comment]
It looks like there's a mistake in the url that kanboard has.  It's trying to download from the tag "v1.3.1", but the correct release tag is just "1.3.1".  Correct url should be "https://github.com/Confexion/Greenwing/releases/download/1.3.1/Greenwing.zip".  I've made a PR for the Kanboard website, so hopefully this should get fixed shortly.  Also, it looks like the version number in your plugin file is missing the minor version update (shows as 1.3.0 instead of 1.3.1).

**Comment by suniahk** [comment]
Just to follow up, the download issue should be fixed.   Plugin version number in Plugins.php still needs to be fixed but that won't stop you from installing.  If you still have problems please update this issue, otherwise @jbaubree it's probably safe to close this one.
